# Generated by Django 4.2.2 on 2023-06-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('College_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('subjects', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InterBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(max_length=3.2)),
                ('state', models.CharField(max_length=20)),
                ('College_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='Student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
